export { default as Cast } from './Details/Cast/Cast'
export { default as Details } from './Details/Details'
export { default as Info } from './Details/Info/Info'
export { default as Videos } from './Details/Videos/Videos'
export { default as Discover } from './Discover/Discover'
export { default as Home } from './Home/Home'
export { default as Results } from './Results/Results'
export { default as ResultsCard } from './Results/ResultsCard'
